version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rootroot
      MARIADB_ROOT_HOST: localhost
      MARIADB_DATABASE: nestapi